language: cpp

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      compiler: gcc-6
      env: COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

    - os: linux
      compiler: clang-3.8
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8


script:
  - $COMPILER --version
  - CXX=$COMPILER ./run_tests.sh
