language: cpp

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      compiler: gcc-6
      env: CXX=g++-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - os: linux
      compiler: clang-3.9
      env: CXX=clang++-3.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.9']


script:
  - $CXX --version
  - ./run_tests.sh
