language: cpp

dist: trusty
sudo: required

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CC_COMPILER=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - os: linux
      compiler: clang
      env: CC_COMPILER=clang-3.9 CXX_COMPILER=clang++-3.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.9']


script:
  - $CXX_COMPILER --version
  - CC="$CC_COMPILER" CXX="CXX_COMPILER" ./run_tests.sh
